version: '3.8'
services:

  postgres:
   image: postgres:13.5
   restart: unless-stopped
   env_file:
     - .env
   volumes:
    - postgres:/var/lib/postgresql/data
   ports:
    - '5432:5432'
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DATABASE_URL}"]
     interval: 10s
     timeout: 5s
     retries: 5



volumes:
  postgres:
